@echo off
cd ftp
del  *.bak *.cod *.lob *.fnd *.err *.tmp
cd ..\engine
del   *.bak *.cod *.lob *.fnd *.err *.tmp
cd ..\debug
del   *.bak *.cod *.lob *.fnd *.err *.tmp
cd ..\include
del   *.bak *.lob *.fnd *.err *.tmp
cd ..\net\enet
del   *.bak *.lob *.cod *.fnd *.err *.tmp
cd ..\..\vs
del   *.bak *.cod *.lob *.fnd *.err *.tmp
cd ..\rg
del   *.bak *.cod *.lob *.fnd *.err *.tmp
cd ..\ftp
del   *.bak *.cod *.lob *.fnd *.err *.tmp
cd ..\minitel
del   *.bak *.cod *.lob *.fnd *.err *.tmp
cd ..\lpr
del   *.bak *.cod *.lob *.fnd *.err *.tmp
cd ..\tek
del   *.bak *.cod *.lob *.fnd *.err *.tmp
cd ..\finger
del   *.bak *.cod *.lob *.fnd *.err *.tmp
cd ..\rexec
del   *.bak *.cod *.lob *.fnd *.err *.tmp
cd ..\setclock
del   *.bak *.cod *.lob *.fnd *.err *.tmp
cd ..\rsh
del   *.bak *.cod *.lob *.fnd *.err *.tmp
cd ..\telpass
del   *.bak *.cod *.lob *.fnd *.err *.tmp
cd ..\net14
del   *.bak *.cod *.lob *.fnd *.err *.tmp
cd ..\whois
del   *.bak *.cod *.lob *.fnd *.err *.tmp
cd ..\lint
del  *.lob del *.err
cd ..\lib
del  *.bak *.lst *.lob *.fnd *.err *.tmp
cd ..

