/*
*    MOUSE.H
*    Header file for Mouse specific things.
****************************************************************************
*                                                                          *
*      NCSA Telnet for the PC                                              *
*      by Tim Krauskopf, VT100 by Gaige Paulsen, Tek by Aaron Contorer     *
*                                                                          *
*      National Center for Supercomputing Applications                     *
*      152 Computing Applications Building                                 *
*      605 E. Springfield Ave.                                             *
*      Champaign, IL  61820                                                *
*                                                                          *
*      This program is in the public domain.                               *
*                                                                          *
****************************************************************************
*   Revisions:
*	10/20/90	 Version 2.3 Andrew Tridgell
*/

#ifndef MOUSE_H
#define MOUSE_H

#define n_chkchar nm_chkchar
#define n_scrlck nm_scrlck

#endif	/* MOUSE_H */
