/*
*    ncsa.h
*
****************************************************************************
*                                                                          *
*                                                                          *
*      NCSA Telnet                                                         *
*      by Tim Krauskopf, VT100 by Gaige Paulsen, Tek by Aaron Contorer     *
*                                                                          *
*      National Center for Supercomputing Applications                     *
*      152 Computing Applications Building                                 *
*      605 E. Springfield Ave.                                             *
*      Champaign, IL  61820                                                *
*                                                                          *
****************************************************************************
*
*   Definitions for general things used al throughout NCSA networking
*   tools.
*
*       Added - December 12, 1991 by Quincey Koziol
*/

#ifndef NCSA_H
#define NCSA_H

/* Exception checking macro */
#define EXCHECK(a,b)    if(a) goto b

#endif /* NCSA_H */

