#ifndef NKEYS_H
#define NKEYS_H
/*  
*  Definitions of keys returned by n_getchar()
*  Compatible with the codes returned for Kermit
*/
#define F1   315
#define F2   316
#define F3   317
#define F4   318
#define F5   319
#define F6   320
#define F7   321
#define F8   322
#define F9   323
#define F10  324
#define F11	 389
#define F12	 390
#define SF1	 852
#define SF2  853
#define SF3  854
#define SF4  855
#define SF5  856
#define SF6  857
#define SF7  858
#define SF8  859
#define SF9  860
#define SF10 861
#define SF11 903
#define SF12 904
#define CF1  1374
#define CF2  1375
#define CF3  1376
#define CF4  1377
#define CF5  1378
#define CF6  1379
#define CF7  1380
#define CF8  1381
#define CF9  1382
#define CF10 1383
#define CF11 1417
#define CF12 1418
#define ALT1 2424
#define ALT2 2425
#define ALT3 2426
#define ALT4 2427
#define ALT5 2428
#define ALT6 2429
#define ALT7 2430
#define ALT8 2431
#define ALT9 2432
#define ALT0 2433
#define AF1  2408
#define AF2  2409
#define AF3  2410
#define AF4  2411
#define AF5  2412
#define AF6  2413
#define AF7  2414
#define AF8  2415
#define AF9  2416
#define AF10 2417
#define AF11 2443
#define AF12 2444
#define CTRLPRTSC	1394	/* Ctrl PrtSc	*/
#define BACKSPACE	270 	/* Backspace	*/

#define HOME		327 	/* HOME key		*/
#define CURLF		331 	/* <-			*/
#define ENDKEY		335 	/* END key		*/
#define CURUP		328 	/* up arrow		*/
#define CURDN		336 	/* down arrow	*/
#define PGUP		329 	/* PgUp			*/
#define CURRT		333 	/* ->			*/
#define PGDN		337 	/* PgDn			*/
#define INSERT		338 	/* Ins			*/
#define DELETE		339 	/* Del			*/
#define CTRLHOME	1399	/* Ctrl Home	*/
#define CTRLCURLF	1395	/* Ctrl <-		*/
#define CTRLEND		1397	/* Ctrl End		*/
#define CTRLPGUP	1412	/* Ctrl PgUp	*/
#define CTRLCURRT	1396	/* Ctrl ->		*/
#define CTRLPGDN	1398	/* Ctrl PgDn	*/

#define E_HOME		4423	/* Enhanced HOME key	*/
#define E_CURLF		4427	/* Enhanced <-			*/
#define E_ENDKEY	4431	/* Enhanced END key		*/
#define E_CURUP		4424	/* Enhanced up arrow	*/
#define E_CURDN		4432	/* Enhanced down arrow	*/
#define E_PGUP		4425	/* Enhanced PgUp		*/
#define E_CURRT		4429	/* Enhanced ->			*/
#define E_PGDN		4433	/* Enhanced PgDn		*/
#define E_INSERT	4434	/* Enhanced Ins			*/
#define E_DELETE	4435	/* Enhanced Del			*/
#define E_CTRLHOME	5495	/* Enhanced Ctrl Home	*/
#define E_CTRLCURLF	5491	/* Enhanced Ctrl <-		*/
#define E_CTRLEND	5493	/* Enhanced Ctrl End	*/
#define E_CTRLPGUP	5508	/* Enhanced Ctrl PgUp	*/
#define E_CTRLCURRT	5492	/* Enhanced Ctrl ->		*/
#define E_CTRLPGDN	5494	/* Enhanced Ctrl PgDn	*/

#define TAB			271		/* Tab			*/
#define REVTAB		783 	/* Shift Tab	*/
#define ALTMINUS	2434	/* Alt -		*/
#define ALTEQUAL	2435	/* Alt =		*/
#define ALTA 2334
#define ALTB 2352
#define ALTC 2350
#define ALTD 2336
#define ALTE 2322
#define ALTF 2337
#define ALTG 2338
#define ALTH 2339
#define ALTI 2327
#define ALTJ 2340
#define ALTK 2341
#define ALTL 2342
#define ALTM 2354
#define ALTN 2353
#define ALTO 2328
#define ALTP 2329
#define ALTQ 2320
#define ALTR 2323
#define ALTS 2335
#define ALTT 2324
#define ALTU 2326
#define ALTV 2351
#define ALTW 2321
#define ALTX 2349
#define ALTY 2325
#define ALTZ 2348
#define THENUL 1283
#define EXIT_TELNET	1888

#endif
